makecode:
  target: microbit
  platform: microbit
  home_url: https://makecode.microbit.org/
#theme: jekyll-theme-slate
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
include:
  - assets
  - README.md
