name: MakeCode

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
    tags:
      - "v*.*.*"

  # Run workflow manually
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          npm install -g pxt
          pxt target microbit
      - name: build
        run: |
          pxt install
          pxt build --cloud
        env:
          CI: true
      #- name: Test
        #run: cat Release.txt
      - name: Release prep
        run: |
          cd /home/runner/work/flappy-bird/flappy-bird/built/
          mv binary.hex flappy-bird.hex
      - name: Release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          files: /home/runner/work/flappy-bird/flappy-bird/built/binary.hex
          tag_name: "automated-release"
          name: "Flappy-Bird(automated release)"
          body: "Automated .hex file release."
          #prerelease: true
          #^^^change this when no longer prerelease ^^^.
